import {DocumentTextIcon} from '@sanity/icons/DocumentText'
import {defineArrayMember, defineField, defineType} from 'sanity'

export const contactPage = defineType({
  name: 'contactPage',
  title: 'Contact gallery',
  type: 'document',
  icon: DocumentTextIcon,
  fields: [
    defineField({
      name: 'title',
      title: 'Form title',
      type: 'string',
      initialValue: 'Get in touch with us',
      validation: (rule) => rule.required(),
      hidden: true,
    }),
    defineField({
      name: 'gallery',
      title: 'Contact image gallery',
      type: 'array',
      of: [defineArrayMember({type: 'projectImage'})],
      validation: (rule) => rule.min(1),
    }),
    defineField({
      name: 'intro',
      title: 'Form introduction',
      type: 'text',
      rows: 3,
      initialValue: "Share your vision. We'll take it from there.",
      hidden: true,
    }),
    defineField({
      name: 'nameLabel',
      title: 'Name label',
      type: 'string',
      initialValue: 'Nombre',
      validation: (rule) => rule.required(),
      hidden: true,
    }),
    defineField({
      name: 'emailLabel',
      title: 'Email label',
      type: 'string',
      initialValue: 'Email',
      validation: (rule) => rule.required(),
      hidden: true,
    }),
    defineField({
      name: 'inquiryLabel',
      title: 'Inquiry type label',
      type: 'string',
      initialValue: 'Tipo de consulta',
      validation: (rule) => rule.required(),
      hidden: true,
    }),
    defineField({
      name: 'messageLabel',
      title: 'Message label',
      type: 'string',
      initialValue: 'Mensaje',
      validation: (rule) => rule.required(),
      hidden: true,
    }),
    defineField({
      name: 'submitLabel',
      title: 'Submit label',
      type: 'string',
      initialValue: 'Enviar',
      validation: (rule) => rule.required(),
      hidden: true,
    }),
    defineField({
      name: 'inquiryOptions',
      title: 'Inquiry options',
      type: 'array',
      of: [defineArrayMember({type: 'contactInquiryOption'})],
      validation: (rule) => rule.min(1),
      hidden: true,
    }),
    defineField({
      name: 'seoTitle',
      title: 'Contact page SEO title',
      type: 'string',
      validation: (rule) => rule.max(60),
      hidden: true,
    }),
    defineField({
      name: 'seoDescription',
      title: 'Contact page SEO description',
      type: 'text',
      rows: 3,
      validation: (rule) => rule.max(160),
      hidden: true,
    }),
  ],
})
